export {default as Home} from './home'
export {default as About} from './about'
export {default as Contact} from './contact'
export {default as Portfolio} from './portfolio'
export {default as Resume} from './resume'
export {default as Skills} from './skills'